import {
  Leaf,
  Apple,
  ClipboardCheck,
  DollarSign,
  Store,
  Scale,
  Handshake,
  BarChart3,
  PieChart,
  Users2,
  Megaphone,
  MessageSquare,
  Tag,
  ShoppingCart,
  QrCode,
  Receipt,
  Settings,
  Repeat,
  Code,
  Layers,
  TestTube,
  Monitor,
  Zap,
  GitBranch,
  LayoutDashboard,
  ShoppingBag,
  ShieldCheck,
  Globe,
} from "lucide-react"

export type Workflow = {
  id: string
  title: string
  description: string
  icon: React.ComponentType<{ className?: string }>
  color: string
  steps: Array<{ label: string; description: string }>
  features: string[]
  stats: { time: string; reach: string }
}

export type WorkflowSection = {
  title: string
  subtitle: string
  workflows: Workflow[]
}

export type CompanyWorkflows = {
  company: string
  sections: WorkflowSection[]
}

export const companyWorkflows: Record<string, CompanyWorkflows> = {
  "Passion Geek (FreshMoe)": {
    company: "Passion Geek (FreshMoe)",
    sections: [
      {
        title: "Procurement — supplier.freshmoe.com",
        subtitle: "Supplier onboarding, purchase orders, quality intake, and supplier settlements",
        workflows: [
          {
            id: "supplier-onboarding",
            title: "Supplier Onboarding",
            description: "Register and verify suppliers with details, product profiles, and supply agreements.",
            icon: Leaf,
            color: "text-emerald-500",
            steps: [
              { label: "Supplier Registration", description: "Collect supplier info — location, business size, product types, and supply capacity." },
              { label: "Document Verification", description: "Verify business licenses, certifications, and compliance documents." },
              { label: "Quality Baseline", description: "Initial quality assessment of product samples to establish grade standards." },
              { label: "Supply Agreement", description: "Set supply terms — minimum quantities, quality expectations, and base pricing." },
              { label: "Account Activation", description: "Supplier activated in system with ability to list available products and receive orders." },
            ],
            features: ["Self-service signup", "Document verification", "Quality baseline", "Supply contracts"],
            stats: { time: "2-day setup", reach: "100% verified" },
          },
          {
            id: "purchase-orders",
            title: "Purchase Orders & Sourcing",
            description: "Create purchase orders for suppliers, negotiate buy prices, and schedule product pickup.",
            icon: Apple,
            color: "text-green-500",
            steps: [
              { label: "Demand Signal", description: "System identifies product needs based on B2B orders, forecasts, and inventory levels." },
              { label: "Supplier Matching", description: "Match demand with available suppliers by product type, quantity, and proximity." },
              { label: "Price Negotiation", description: "Negotiate buy price per unit based on grade, market rates, and volume." },
              { label: "PO Generation", description: "Auto-generate purchase order with agreed price, quantity, and pickup schedule." },
              { label: "Confirmation", description: "Supplier confirms availability and pickup window in the system." },
            ],
            features: ["Demand-driven sourcing", "Supplier matching", "Price negotiation", "Auto POs"],
            stats: { time: "50% faster sourcing", reach: "95% fill rate" },
          },
          {
            id: "intake-quality",
            title: "Intake & Quality Inspection",
            description: "Receive products from suppliers with quality grading, weight verification, and price adjustments.",
            icon: ClipboardCheck,
            color: "text-amber-500",
            steps: [
              { label: "Arrival Logging", description: "Log delivery from supplier — timestamp, PO reference, and expected quantities." },
              { label: "Weight Verification", description: "Weigh received products and compare against PO quantities." },
              { label: "Quality Grading", description: "Grade products (A/B/C) based on freshness, size, blemishes, and ripeness." },
              { label: "Price Adjustment", description: "Adjust final buy price based on actual grade and weight received." },
              { label: "Acceptance / Rejection", description: "Accept products into inventory or reject with documented reason for supplier feedback." },
            ],
            features: ["Weight verification", "Grading system", "Price adjustment", "Reject workflow"],
            stats: { time: "90% less errors", reach: "98% grade accuracy" },
          },
          {
            id: "supplier-payments",
            title: "Supplier Settlements",
            description: "Process payments to suppliers based on accepted quantities and agreed pricing terms.",
            icon: DollarSign,
            color: "text-blue-500",
            steps: [
              { label: "Invoice Generation", description: "Auto-generate settlement invoice from accepted intake records." },
              { label: "Supplier Review", description: "Supplier reviews and confirms settlement details in their portal." },
              { label: "Approval", description: "Procurement manager approves settlement for payment processing." },
              { label: "Payment Disbursement", description: "Execute payment via bank transfer, mobile money, or cash pickup." },
              { label: "Reconciliation", description: "Match payment records with bank statements and supplier confirmations." },
            ],
            features: ["Auto invoicing", "Supplier portal", "Multi-payment", "Reconciliation"],
            stats: { time: "3-day payment", reach: "100% traceable" },
          },
        ],
      },
      {
        title: "B2B Sales — b2b.freshmoe.com",
        subtitle: "Buyer onboarding, catalog pricing, order fulfillment, and collections",
        workflows: [
          {
            id: "buyer-onboarding",
            title: "B2B Buyer Onboarding",
            description: "Register B2B buyers (restaurants, retailers, wholesalers) with credit assessment and pricing tier setup.",
            icon: Store,
            color: "text-indigo-500",
            steps: [
              { label: "Business Registration", description: "Collect buyer details — business type, license, delivery address, and contact info." },
              { label: "Credit Assessment", description: "Evaluate creditworthiness and assign credit limit and payment terms." },
              { label: "Pricing Tier Assignment", description: "Assign pricing tier (standard, premium, VIP) with corresponding margins." },
              { label: "Account Activation", description: "Buyer gains access to catalog with their tier pricing and can place orders." },
              { label: "First Order Support", description: "Sales rep assists with first order setup and onboarding walkthrough." },
            ],
            features: ["Business verification", "Credit limits", "Pricing tiers", "First-order support"],
            stats: { time: "1-day activation", reach: "90% repeat buyers" },
          },
          {
            id: "catalog-pricing",
            title: "Catalog & Pricing Management",
            description: "FreshMoe sets sell prices with margins, manages product catalog, and handles dynamic pricing.",
            icon: Scale,
            color: "text-rose-500",
            steps: [
              { label: "Inventory Availability", description: "System checks available stock from intake and grades for catalog listing." },
              { label: "Cost Calculation", description: "Calculate per-unit cost including purchase price, logistics, storage, and wastage." },
              { label: "Margin Application", description: "Apply FreshMoe target margin based on product category and buyer tier." },
              { label: "Price Publishing", description: "Publish sell prices to catalog — buyers see their tier-specific pricing." },
              { label: "Dynamic Adjustments", description: "Auto-adjust prices based on shelf life, stock levels, and market demand." },
            ],
            features: ["Auto cost calculation", "Margin control", "Tier pricing", "Dynamic pricing"],
            stats: { time: "Instant updates", reach: "35% average margin" },
          },
          {
            id: "order-fulfillment",
            title: "Order Fulfillment",
            description: "Process B2B buyer orders — picking, packing, quality check, and delivery scheduling.",
            icon: Handshake,
            color: "text-purple-500",
            steps: [
              { label: "Order Receipt", description: "Buyer places order through portal, app, or sales rep with produce selection and quantities." },
              { label: "Inventory Allocation", description: "System reserves stock from warehouse based on FIFO and shelf-life priority." },
              { label: "Picking & Packing", description: "Warehouse team picks allocated stock with quality check before packing." },
              { label: "Delivery Scheduling", description: "Assign delivery vehicle and time slot based on buyer preferences and route optimization." },
              { label: "Delivery & Receipt", description: "Driver delivers produce, buyer inspects and confirms receipt in the system." },
            ],
            features: ["Auto allocation", "FIFO picking", "Route optimization", "Delivery confirmation"],
            stats: { time: "Same-day fulfillment", reach: "97% on-time" },
          },
          {
            id: "invoicing-collections",
            title: "Invoicing & Collections",
            description: "Generate invoices for delivered orders, track receivables, and manage collections for B2B buyers.",
            icon: BarChart3,
            color: "text-orange-500",
            steps: [
              { label: "Invoice Generation", description: "Auto-generate invoice upon delivery confirmation with itemized pricing." },
              { label: "Payment Tracking", description: "Monitor payment status against due dates based on buyer credit terms." },
              { label: "Reminder Automation", description: "Send automated payment reminders via email/SMS as due date approaches." },
              { label: "Collections Escalation", description: "Escalate overdue accounts with hold on new orders and collection workflow." },
              { label: "Reconciliation", description: "Match received payments to invoices and update buyer credit limits." },
            ],
            features: ["Auto invoicing", "Payment tracking", "Smart reminders", "Credit holds"],
            stats: { time: "60% faster collection", reach: "95% on-time payment" },
          },
        ],
      },
      {
        title: "Portfolio Management — freshmoe.com",
        subtitle: "Product catalog, brand management, and business intelligence",
        workflows: [
          {
            id: "product-catalog",
            title: "Product Catalog Management",
            description: "Centralized catalog for all produce categories, grades, seasonal items, and pricing across all channels.",
            icon: PieChart,
            color: "text-violet-500",
            steps: [
              { label: "Category Setup", description: "Define produce categories (fruits, vegetables, herbs) with subcategories and attributes." },
              { label: "Product Creation", description: "Add products with grade standards, unit of measure, shelf life, and storage requirements." },
              { label: "Pricing Configuration", description: "Set buy price, target margin, and sell price tiers (B2B wholesale, retail, VIP)." },
              { label: "Seasonal Planning", description: "Plan seasonal availability, phase-in/phase-out schedules, and substitute products." },
              { label: "Catalog Publishing", description: "Push updates to B2B portal, retail POS, and marketing channels with version control." },
            ],
            features: ["Multi-channel catalog", "Grade standards", "Seasonal planning", "Version control"],
            stats: { time: "Instant updates", reach: "100% channel sync" },
          },
          {
            id: "brand-management",
            title: "Brand & Channel Management",
            description: "Manage FreshMoe brand presence across B2B, retail stores, and digital channels.",
            icon: Users2,
            color: "text-blue-500",
            steps: [
              { label: "Brand Configuration", description: "Define brand guidelines, logos, color schemes, and messaging templates." },
              { label: "Channel Setup", description: "Configure B2B portal, retail POS, social media, and SMS channels." },
              { label: "Content Scheduling", description: "Schedule brand content, promotions, and announcements across channels." },
              { label: "Performance Tracking", description: "Monitor brand engagement, channel performance, and customer sentiment." },
              { label: "Optimization", description: "Adjust branding strategy based on analytics and customer feedback." },
            ],
            features: ["Multi-channel", "Content scheduling", "Engagement tracking", "Sentiment analysis"],
            stats: { time: "50% more engagement", reach: "3 channels managed" },
          },
          {
            id: "analytics-reporting",
            title: "Analytics & Business Intelligence",
            description: "Real-time dashboards for revenue, margins, inventory turnover, and operational KPIs.",
            icon: BarChart3,
            color: "text-emerald-500",
            steps: [
              { label: "KPI Configuration", description: "Define key metrics — revenue, gross margin, wastage rate, order fulfillment rate." },
              { label: "Dashboard Creation", description: "Build role-based dashboards for procurement, sales, and executive views." },
              { label: "Automated Reports", description: "Schedule daily, weekly, and monthly reports with PDF export and email delivery." },
              { label: "Trend Analysis", description: "Historical data analysis for seasonal patterns, price trends, and demand forecasting." },
              { label: "Alert Configuration", description: "Set threshold alerts for critical metrics like stock levels, margin drops, and overdue payments." },
            ],
            features: ["Role-based dashboards", "Automated reports", "Trend analysis", "Smart alerts"],
            stats: { time: "Real-time data", reach: "15+ KPIs tracked" },
          },
        ],
      },
      {
        title: "Marketing Management",
        subtitle: "Social media, SMS campaigns, and promotions across channels",
        workflows: [
          {
            id: "social-media",
            title: "Social Media Management",
            description: "Schedule, publish, and track social media content across Facebook, Instagram, and TikTok.",
            icon: Megaphone,
            color: "text-pink-500",
            steps: [
              { label: "Content Creation", description: "Create posts with product photos, pricing, and promotional content." },
              { label: "Approval Pipeline", description: "Manager reviews and approves content before publishing." },
              { label: "Scheduled Publishing", description: "Auto-publish at optimal times based on audience engagement patterns." },
              { label: "Engagement Monitoring", description: "Track comments, shares, and mentions with response workflows." },
              { label: "Performance Reports", description: "Weekly analytics on reach, engagement, and conversion from social traffic." },
            ],
            features: ["Multi-platform", "Auto-scheduling", "Approval workflow", "Analytics"],
            stats: { time: "10 hrs/week saved", reach: "3x social reach" },
          },
          {
            id: "sms-campaigns",
            title: "SMS & Notification Campaigns",
            description: "Bulk SMS campaigns for promotions, daily price lists, and transactional notifications.",
            icon: MessageSquare,
            color: "text-green-500",
            steps: [
              { label: "Audience Segmentation", description: "Group buyers by purchase history, location, and product preferences." },
              { label: "Campaign Design", description: "Create SMS templates with daily prices, weekly specials, and promotional offers." },
              { label: "Scheduling", description: "Schedule campaign sends for optimal timing (e.g., morning price lists)." },
              { label: "Delivery Tracking", description: "Monitor delivery status, open rates, and response tracking." },
              { label: "ROI Analysis", description: "Measure campaign impact on order volume and revenue per segment." },
            ],
            features: ["Smart segments", "Template library", "Delivery tracking", "ROI analysis"],
            stats: { time: "95% delivery rate", reach: "30% order lift" },
          },
          {
            id: "promotions",
            title: "Promotions & Discounts",
            description: "Create and manage promotional campaigns, flash sales, and volume discount offers.",
            icon: Tag,
            color: "text-orange-500",
            steps: [
              { label: "Promotion Design", description: "Define promotion type — flash sale, volume discount, seasonal offer, or bundle deal." },
              { label: "Eligibility Rules", description: "Set target audience, minimum order value, and product scope." },
              { label: "Launch & Distribute", description: "Activate promotion across POS, B2B portal, SMS, and social media simultaneously." },
              { label: "Real-Time Monitoring", description: "Track redemption rates, revenue impact, and inventory depletion." },
              { label: "Post-Campaign Review", description: "Analyze promotion effectiveness and customer response for future planning." },
            ],
            features: ["Multi-channel launch", "Eligibility rules", "Live monitoring", "Post-analysis"],
            stats: { time: "5x promo ROI", reach: "40% redemption rate" },
          },
        ],
      },
      {
        title: "Retail POS — freshmoe.com Stores",
        subtitle: "POS transactions, store inventory, and per-store analytics",
        workflows: [
          {
            id: "pos-transactions",
            title: "POS Transactions",
            description: "Fast checkout for FreshMoe retail stores with produce weighing, pricing, and receipt generation.",
            icon: ShoppingCart,
            color: "text-indigo-500",
            steps: [
              { label: "Product Selection", description: "Scan barcode or search by name for packaged items; weigh fresh produce at integrated scale." },
              { label: "Price Calculation", description: "Auto-calculate price based on weight, retail pricing, and any active promotions." },
              { label: "Payment Processing", description: "Accept cash, card, or mobile payment with real-time transaction confirmation." },
              { label: "Receipt Generation", description: "Print or digital receipt with item details, taxes, and loyalty points earned." },
              { label: "Inventory Deduction", description: "Real-time inventory update with wastage tracking for perishable items." },
            ],
            features: ["Scale integration", "Multi-payment", "Promo support", "Auto inventory"],
            stats: { time: "Under 30 sec checkout", reach: "100% inventory sync" },
          },
          {
            id: "store-inventory",
            title: "Store Inventory Management",
            description: "Track stock levels, shelf life, and reorder points for each retail store location.",
            icon: QrCode,
            color: "text-teal-500",
            steps: [
              { label: "Stock Receiving", description: "Log incoming stock from warehouse with barcode scanning and quantity verification." },
              { label: "Shelf-Life Tracking", description: "Track expiry dates and automatically flag items approaching shelf life limits." },
              { label: "Reorder Alerts", description: "Auto-generate reorder requests to warehouse when stock falls below minimum levels." },
              { label: "Stock Adjustment", description: "Record wastage, shrinkage, and damage with reason codes for cost tracking." },
              { label: "Daily Reconciliation", description: "End-of-day stock count reconciliation against system records." },
            ],
            features: ["Barcode scanning", "Shelf-life alerts", "Auto reorder", "Wastage tracking"],
            stats: { time: "60% less wastage", reach: "99% stock accuracy" },
          },
          {
            id: "store-analytics",
            title: "Store Performance & Analytics",
            description: "Per-store dashboards tracking sales, margins, peak hours, and top-selling products.",
            icon: Receipt,
            color: "text-amber-500",
            steps: [
              { label: "Sales Tracking", description: "Real-time sales data per store, per category, and per product." },
              { label: "Margin Analysis", description: "Track actual margins vs target margins with cost breakdown per item." },
              { label: "Peak Hour Analysis", description: "Identify busiest hours and optimize staffing and stock preparation." },
              { label: "Top Products", description: "Rank products by revenue, volume, and margin contribution." },
              { label: "Comparative Reports", description: "Compare performance across store locations with trend analysis." },
            ],
            features: ["Real-time sales", "Margin tracking", "Peak analysis", "Store comparison"],
            stats: { time: "Daily insights", reach: "25% margin improvement" },
          },
        ],
      },
      {
        title: "Franchise Management — franchise.freshmoe.com",
        subtitle: "Franchise onboarding, inventory distribution, revenue sharing, and performance monitoring",
        workflows: [
          {
            id: "franchise-onboarding",
            title: "Franchise Onboarding",
            description: "Register and configure new franchise stores with inventory setup, POS configuration, and training.",
            icon: Store,
            color: "text-blue-500",
            steps: [
              { label: "Franchise Application", description: "Collect franchisee details — location, store size, capital investment, and business plan." },
              { label: "Approval & Contract", description: "Review application, negotiate franchise terms, and sign digital franchise agreement." },
              { label: "Store Setup", description: "Configure POS system, assign store code, set up inventory, and integrate with central warehouse." },
              { label: "Training", description: "Train franchisee staff on POS operations, inventory management, and reporting dashboards." },
              { label: "Grand Opening", description: "Launch store with initial marketing campaign and head office support." },
            ],
            features: ["Digital contracts", "Store configuration", "Staff training", "Launch support"],
            stats: { time: "2-week onboarding", reach: "100% trained staff" },
          },
          {
            id: "inventory-distribution",
            title: "Warehouse to Franchise Distribution",
            description: "Central warehouse manages inventory distribution to franchise stores based on demand and stock levels.",
            icon: ShoppingCart,
            color: "text-emerald-500",
            steps: [
              { label: "Store Reorder Request", description: "Franchise store submits reorder request based on stock levels and sales forecast." },
              { label: "Warehouse Allocation", description: "Central warehouse checks availability and allocates stock for distribution." },
              { label: "Dispatch Scheduling", description: "Schedule delivery with route optimization for multiple franchise stores." },
              { label: "Store Receiving", description: "Franchise store receives stock, verifies quantities, and logs into store inventory." },
              { label: "Transfer Settlement", description: "Internal transfer settlement between warehouse and franchise for accounting." },
            ],
            features: ["Auto reorder", "Route optimization", "Quantity verification", "Transfer accounting"],
            stats: { time: "Same-day dispatch", reach: "98% accuracy" },
          },
          {
            id: "revenue-sharing",
            title: "Revenue Sharing & Royalties",
            description: "Automated revenue sharing calculations, royalty deductions, and franchisee payout management.",
            icon: DollarSign,
            color: "text-amber-500",
            steps: [
              { label: "Daily Sales Sync", description: "Franchise POS syncs daily sales data to central system for revenue calculation." },
              { label: "Royalty Calculation", description: "Auto-calculate franchise royalty percentage and other contractual deductions." },
              { label: "Franchisee Statement", description: "Generate weekly/monthly revenue statements for franchisee review." },
              { label: "Payout Processing", description: "Process franchisee share payments after deducting royalties, inventory costs, and fees." },
              { label: "Reconciliation", description: "Match payments with bank records and franchisee confirmations." },
            ],
            features: ["Auto sync", "Royalty engine", "Revenue statements", "Payout automation"],
            stats: { time: "Weekly payouts", reach: "100% transparency" },
          },
          {
            id: "franchise-monitoring",
            title: "Franchise Performance Monitoring",
            description: "Central monitoring of franchise store performance, compliance, and brand standards.",
            icon: PieChart,
            color: "text-violet-500",
            steps: [
              { label: "KPI Dashboard", description: "Real-time dashboard showing sales, margins, customer ratings, and compliance scores per franchise." },
              { label: "Compliance Audits", description: "Schedule and conduct brand standard audits — store cleanliness, pricing compliance, service quality." },
              { label: "Alert System", description: "Automated alerts for underperforming stores, compliance violations, or operational issues." },
              { label: "Support Workflow", description: "Trigger support actions — training, inventory assistance, or operational guidance." },
              { label: "Performance Reviews", description: "Quarterly performance reviews with franchisees and improvement action plans." },
            ],
            features: ["Live dashboards", "Compliance audits", "Smart alerts", "Support workflows"],
            stats: { time: "Real-time monitoring", reach: "90% compliance rate" },
          },
        ],
      },
    ],
  },
  "Revelio": {
    company: "Revelio",
    sections: [
      {
        title: "Test Automation & Coverage",
        subtitle: "Comprehensive route testing to minimize errors and enhance platform stability",
        workflows: [
          {
            id: "route-testing",
            title: "Route Test Coverage",
            description: "Systematic test coverage across all application routes with automated regression testing.",
            icon: TestTube,
            color: "text-cyan-500",
            steps: [
              { label: "Route Mapping", description: "Identify all application routes and define test scenarios for each." },
              { label: "Test Case Creation", description: "Write unit, integration, and E2E tests for route handlers and middleware." },
              { label: "Mock Data Setup", description: "Create realistic test data with edge cases for thorough validation." },
              { label: "Automated Execution", description: "Run test suites on every commit with CI/CD pipeline integration." },
              { label: "Coverage Reporting", description: "Track test coverage metrics and identify gaps in route testing." },
            ],
            features: ["E2E testing", "Mock data", "CI integration", "Coverage reports"],
            stats: { time: "90% coverage", reach: "Zero route errors" },
          },
          {
            id: "regression-testing",
            title: "Regression Prevention",
            description: "Automated regression testing to catch breaking changes before deployment.",
            icon: ShieldCheck,
            color: "text-emerald-500",
            steps: [
              { label: "Baseline Tests", description: "Establish baseline test suite covering all critical user journeys." },
              { label: "Change Detection", description: "Automated detection of breaking changes in API responses and UI behavior." },
              { label: "Snapshot Testing", description: "Visual and data snapshots to catch unintended UI and data changes." },
              { label: "Alert Pipeline", description: "Immediate alerts when regression tests fail with detailed failure reports." },
            ],
            features: ["Snapshot testing", "Change detection", "Alert pipeline", "Baseline suite"],
            stats: { time: "Pre-deployment catch", reach: "99% regression prevention" },
          },
        ],
      },
      {
        title: "UI/UX Feature Development",
        subtitle: "Intuitive, responsive interfaces built with Vue.js and Ant Design",
        workflows: [
          {
            id: "feature-development",
            title: "Feature Development Pipeline",
            description: "End-to-end feature development from design to deployment with Vue.js and Ant Design.",
            icon: Monitor,
            color: "text-violet-500",
            steps: [
              { label: "Design Review", description: "Collaborate with designers on component layouts, responsive breakpoints, and interactions." },
              { label: "Component Development", description: "Build reusable Vue.js components using Ant Design patterns." },
              { label: "Responsive Testing", description: "Test across devices and screen sizes for consistent user experience." },
              { label: "User Feedback", description: "Collect user feedback and iterate on UI improvements." },
            ],
            features: ["Vue.js", "Ant Design", "Responsive", "Iterative design"],
            stats: { time: "2-week cycles", reach: "40% UX improvement" },
          },
          {
            id: "component-library",
            title: "Component Library",
            description: "Shared component library for consistent UI across the delivery ecosystem.",
            icon: Layers,
            color: "text-pink-500",
            steps: [
              { label: "Component Catalog", description: "Document and catalog all reusable UI components with usage examples." },
              { label: "Style Guide", description: "Establish design tokens, color palettes, typography, and spacing standards." },
              { label: "Integration", description: "Integrate component library across admin dashboard, shop app, and rider app." },
            ],
            features: ["Design tokens", "Storybook", "Cross-app", "Documentation"],
            stats: { time: "60% faster UI dev", reach: "Consistent across 3 apps" },
          },
        ],
      },
      {
        title: "Database Migration",
        subtitle: "MySQL to MongoDB migration for improved performance and scalability",
        workflows: [
          {
            id: "db-migration",
            title: "MySQL to MongoDB Migration",
            description: "Architected and executed the migration from relational MySQL to document-based MongoDB.",
            icon: GitBranch,
            color: "text-amber-500",
            steps: [
              { label: "Schema Design", description: "Design MongoDB document schemas optimized for the delivery ecosystem data model." },
              { label: "Data Mapping", description: "Map MySQL relational tables to MongoDB collections with embedded documents." },
              { label: "Migration Scripts", description: "Write and test data migration scripts with rollback capability." },
              { label: "Dual-Write Phase", description: "Run dual-write to both databases during transition for data safety." },
              { label: "Cutover & Validation", description: "Switch reads to MongoDB, validate data integrity, and decommission MySQL." },
            ],
            features: ["Zero downtime", "Rollback capability", "Data validation", "Performance gains"],
            stats: { time: "3x query speed", reach: "Zero data loss" },
          },
        ],
      },
      {
        title: "Delivery Ecosystem Integration",
        subtitle: "Unified platform connecting admin dashboard, shop app, and rider app",
        workflows: [
          {
            id: "ecosystem-integration",
            title: "Unified Delivery Platform",
            description: "Integrated admin dashboard, shop user app, and rider app into a cohesive delivery ecosystem.",
            icon: Globe,
            color: "text-blue-500",
            steps: [
              { label: "API Design", description: "Design shared APIs for order management, tracking, and notifications across all apps." },
              { label: "Real-Time Sync", description: "Implement WebSocket-based real-time order status updates across all three platforms." },
              { label: "Order Flow", description: "Build end-to-end order flow from shop placement to rider pickup to delivery confirmation." },
              { label: "Admin Oversight", description: "Admin dashboard provides real-time visibility into all active orders and rider locations." },
            ],
            features: ["Real-time sync", "Shared APIs", "End-to-end flow", "Admin visibility"],
            stats: { time: "Unified platform", reach: "3 apps integrated" },
          },
          {
            id: "rider-dispatch",
            title: "Rider Dispatch & Tracking",
            description: "Automated rider assignment, route optimization, and real-time delivery tracking.",
            icon: Zap,
            color: "text-green-500",
            steps: [
              { label: "Order Assignment", description: "Auto-assign orders to nearest available rider based on location and capacity." },
              { label: "Route Optimization", description: "Calculate optimal delivery routes with real-time traffic adjustments." },
              { label: "Live Tracking", description: "Real-time GPS tracking visible to shop, rider, and admin." },
              { label: "Delivery Confirmation", description: "Photo proof and signature capture for delivery confirmation." },
            ],
            features: ["Auto dispatch", "Route optimization", "Live GPS", "Proof of delivery"],
            stats: { time: "25% faster delivery", reach: "95% on-time" },
          },
        ],
      },
    ],
  },
}
